### ISSUE TITLE
Small significance discrepancies with ED

### ISSUE THREAD

**Issue by samanthalwong** [VERITAS-Observatory/gammapy-tools#54]
After implementing this [gammapy PR](https://github.com/gammapy/gammapy/pull/5270), significances match ED much better than before, but are still up to 25% higher than ED reflected regions (though some are < 1% different). There are still differences with comparing ED RBM as well and carefully matching ring parameters. 

How much of a difference are we okay with and do we have any reasons for the difference? This is a bit degenerate with issue #51, since different counts will lead to different significances and different methods will lead to different significances.

**Comment by steob92** [comment]
Personally I'd take the approach that we're using different software with different ways of "doing things". We shouldn't expect perfect agreement. As long as we understand where the differences are, and otherwise see statistical agreement (where is a different statistical method), I think that's enough.

For example, identically matching event numbers isn't critical if we understand why gammapy drops events that ED/VEGAS otherwise keeps.

Other things like seeing 5 sigma vs 10 sigma... That's a big issue. If we see 5 vs 5.5, with the difference in on/off counts explains the 0.5 difference and we understand why we see the difference... I think that's fine.
