### ISSUE TITLE
 Large offset_max (2.5 deg) needed for dim sources(?)

### ISSUE THREAD

**Issue by steob92** [VERITAS-Observatory/gammapy-tools#58]
From GammaWiki Known issues: 

- Large offset_max (2.5 deg) needed for dim sources(?) e.g., Segue 1. Leads to an error with not being able to stack migration matrix maps in the RBM analysis. Not sure specifically that this is just for dim sources, so future analyses needed to confirm.

**Comment by steob92** [comment]
I'm unsure who made this issue (@matthew-w-lundy, @samanthalwong ) or of its an ED, VEGAS or Gammapy issue. I'll attempt to reproduce with [1.1_rc](https://github.com/VERITAS-Observatory/gammapy-tools/tree/1.1_rc). 

If anyone else has more details, please add them below.

**Comment by samanthalwong** [comment]
From the wiki history it looks like I made it but I honestly don't remember anything about this 😅 I've analyzed Segue with 1.5-2 offset-max since and haven't had any issues with the migration matrix but would be good to confirm!

**Comment by steob92** [comment]
The only thing that sticks out about 2.5 degrees is that we simulate up to 2.0 degrees offset, so 2.5 degrees shouldn't have reliable IRFs. Anything requiring that much FoV coverage would need dedicated simulations.

**Comment by samanthalwong** [comment]
Yeah I get the sense that it was a bandaid fix for a bigger problem that we've since resolved

**Comment by steob92** [comment]
I ran with 2.5, 2.0, 1.9 1.7. I see edge effects with 2.5, 2.0 and 1.9. These are older files I had on disk so I suspect that issue is related to older background smoothing. 

This is a known issue and why we should only use smoothing for selecting runs, not for actual analysis/IRF generation. At the edges of the parameter space, smoothing artificially decreases counts/IRF within the real usable range and artificially increases counts/IRFs outside the real usable range. 

Just on smoothing I'd suggest removing it as a user option from 1.1 onward, such that a default value is used when calculating the KL divergence. The only time a user could actually use it for analysis would be with a `force_smooth` flag or something.

No issues with the migration matix...
![segue1_1 7_deg](https://github.com/user-attachments/assets/f8aba4be-d413-4554-a00e-c064a57a032a)
![segue1_1 9_deg](https://github.com/user-attachments/assets/f2027a4f-fedb-4ba6-85e3-1fa4f1f36d52)
![segue1_2 0_deg](https://github.com/user-attachments/assets/a0e0eaaa-a1bc-47f6-b585-79c4712ec29b)

**Comment by samanthalwong** [comment]
I've been testing both smoothed and unsmoothed bkgs with current scripts and don't see any non-negligible differences in the sky maps or other output (though in cases of low background statistics unsmoothed will perform worse, e.g., runwise). If you have any examples of where smoothing is causing problems but not smoothing is not, I'd be curious to see where this is happening.

I have seen issues with using offset-max > 1.75 for both cases though and although we use 2 deg for ED, I think it might be better to keep it on the small side - I think it's probably best to keep it << 2 deg.

**Comment by steob92** [comment]
The plots need and analysis needs to be fleshed out some more but see attached. The background rate is highly dependent on the smoothing angle used:

![image](https://github.com/user-attachments/assets/92cb0dc6-b6da-4fbc-9e3d-6ef236de28eb)

**Comment by samanthalwong** [comment]
I can't replicate the sky map artifacts you're seeing (see below; I actually get the opposite where no smoothing has the edge effects but smoothing doesn't), but I believe that the smoothing impact on background rate is due to improper convolution with the Gaussian kernel.

I'll look into better ways to implement some sort of interpolation, whether it be convolving with a Gaussian with proper normalization or spline fitting, which is more similar to ED but also to how HESS smooths their 3D bkgs. 

I'll open a different issue for this to keep better track of the actual issue and not my original issue on the wiki, which I haven't run into since we've resolved other issues in gammapy/gammapy-tools. We can reopen if this comes up again.

![image](https://github.com/user-attachments/assets/fbd086c5-57e4-4c5a-8457-6a802cf7d779)
![image](https://github.com/user-attachments/assets/016f814d-db68-4b09-aeff-1907739b3a95)
